from typing import List, Dict,Any,Union
from typing import List
import string
import math
import torch

# hindsight positive language templates
hp_templates=[
    "Great job on moving forward so effectively!",
    "Well done on making such a smart move!",
    "Your progress is outstanding; keep it up!",
    "That was a wise choice—well executed!",
    "You're doing really well; that's a significant improvement!",
    "You're clearly on the right path now.",
    "Impressive decision! You're really thinking ahead.",
    "Your action was spot-on—great thinking!",
    "Superb progress! You're really advancing.",
    "Keep this momentum going; you're doing fantastic!",
    "You handled that brilliantly!",
    "I'm proud to see how well you're doing.",
    "You made a very astute decision there!",
    "Your efforts are really paying off!",
    "That's a solid move you've just made.",
    "Bravo! Your skills are shining through.",
    "You've shown great insight with that move.",
    "Your choice was very prudent.",
    "You're making real headway now!",
    "That's a commendable action. Well done!",
    "Your strides in improvement are clear.",
    "You're excelling at this, keep going!",
    "Marvelous execution—your planning paid off!",
    "You're steering things in the right direction.",
    "That was a pivotal change you made.",
    "You've really set a new standard with that.",
    "Remarkable approach—very strategic!",
    "Your initiative is really impressive.",
    "That's a masterful way to handle it!",
    "You've shown true acumen with that decision.",
    "Your move was ingenious!",
    "A very clever approach—well played!",
    "You're pushing the boundaries excellently.",
    "What a sharp move—truly effective!",
    "You've captured the essence of good strategy.",
    "That maneuver was first-rate.",
    "Your approach is proving successful.",
    "What a tactful way to proceed!",
    "You're mastering this beautifully.",
    "A powerful move—very inspiring!",
    "You've really embraced the challenge successfully.",
    "That adjustment was key—nice work!",
    "Your efforts are bearing fruit wonderfully.",
    "A very sophisticated tactic—impressive!",
    "You're leading by example now.",
    "What an innovative approach!",
    "You've adopted a winning strategy.",
    "That was a strong play—well navigated!",
    "Your actions speak volumes of your capability.",
    "A very forward-thinking step!",
    "You're crafting your path masterfully.",
    "That was a clever twist—well thought out!",
    "You're setting a high bar with moves like that.",
    "An effective strategy—clearly successful!",
    "You're charting a successful course.",
    "That adjustment has made a big difference.",
    "You've pivoted beautifully there.",
    "That's an exemplary way to manage it!",
    "Your insight was perfectly applied there.",
    "A dynamic change—excellently handled!",
    "Nicely done—that's a strategic advance!",
    "You've taken a very promising step forward.",
    "Excellent maneuver; your judgment is top-notch!",
    "That initiative was exactly what was needed—great job!",
    "Your action sets a new benchmark—remarkably done!",
    "You're paving the way brilliantly.",
    "Your foresight in that decision is commendable.",
    "That was a sharp and effective decision—well done!",
    "You're showcasing great prowess in your moves.",
    "Your continual progress is impressive—keep it up!",
    "You've just demonstrated perfect timing and execution!",
    "I'm thrilled to see such smart choices from you.",
    "Your ability to innovate is clear and effective.",
    "Your dedication is paying dividends—well executed!",
    "That's a robust approach you've taken—impressive!",
    "Cheers to that clever solution—exceptionally handled!",
    "You've just raised the bar with your recent move.",
    "Your insight into making that choice was brilliant.",
    "Continued success like this is no small feat—amazing work!",
    "That was a crucial improvement—excellent foresight!",
    "You're making all the right decisions—fantastic!",
    "Your tactical approach is yielding great results.",
    "You've got a knack for this—terrific job!",
    "That's the spirit of innovation at work—splendid!",
    "You've transformed challenges into opportunities—well played!",
    "That change was absolutely pivotal—well spotted!",
    "You're navigating this perfectly!",
    "What a strategic victory—very smart!",
    "You've mastered the art of making timely decisions.",
    "That was not just good, it was phenomenal!",
    "Your proactive steps are leading to great outcomes.",
    "This is a textbook example of doing it right!",
    "You've implemented that plan flawlessly—excellent!",
    "That's a game-changing move—perfectly executed!",
    "You've outperformed expectations with that strategy.",
    "Your approach is both innovative and effective.",
    "You're proving to be a strategic thinker—well done!",
    "That was a masterstroke—truly impressive!",
    "You're leading the way with your actions.",
    "An outstanding application of your skills—superb!",
    "Your tactical moves are spot-on and commendable.",
    "You've turned the tide in your favor—excellent strategy!",
    "What a profound impact your decision has made!",
    "You're crafting a success story with each step.",
    "That was a deeply insightful move—great foresight!",
    "You've matched your skills with perfect execution.",
    "That was a brilliantly executed plan—congratulations!",
    "You're making waves with your strategic insight.",
    "An exceptional outcome from a well-thought strategy!",
    "You're setting benchmarks in strategic thinking.",
    "That was an extraordinarily effective maneuver!",
    "You've excelled in turning plans into action.",
    "What a commendable way to tackle that challenge!",
    "You're defining excellence with your strategies.",
    "That decision was a stroke of genius—well captured!",
    "Your strategic planning is paying off wonderfully.",
    "You're really shaping things to your advantage.",
    "That was a cutting-edge decision—superbly handled!",
    "You're demonstrating exceptional problem-solving skills.",
    "An absolutely stellar performance—keep this up!",
    "You've just redefined what success looks like in this area.",
    "Your insightful actions are leading to great achievements!",
    "Brilliantly executed—your strategies are paying off.",
    "You're doing a fantastic job steering this project!",
    "Excellent work making such a crucial improvement!",
    "Your ability to adapt and overcome is remarkable!",
    "Impressively handled—your efforts are very promising!",
    "You've really outperformed with that strategic move!",
    "That was a groundbreaking step—absolutely phenomenal!",
    "You've made a decisive impact with your actions!",
    "Your quick thinking and sharp execution are unmatched!",
    "That was a critical and well-managed step!",
    "Superb decision-making—your progress is impressive!",
    "You've shown great command in navigating this challenge.",
    "What a powerful approach—extremely effective!",
    "You've exceeded all expectations with that move!",
    "Your expertise is clearly shining through!",
    "What a remarkable display of talent and foresight!",
    "You're making exceptional strides—keep it up!",
    "That was an outstanding choice—strategically sound!",
    "Your approach is setting a new standard for excellence!",
    "Innovative and wise—your moves are masterclass!",
    "You've taken a giant leap forward with that action!",
    "Your decision-making skills are truly top-notch!",
    "That was a perfectly executed plan—stellar job!",
    "You're transforming challenges into successes!",
    "Your strategic foresight is leading to great outcomes.",
    "That move was a masterpiece of tactical planning!",
    "Exceptionally handled—from planning to execution!",
    "You're setting the pace for everyone—magnificent!",
    "You've clearly mastered this task—what an achievement!",
    "Your efforts have catalyzed significant progress!",
    "That was a prime example of expert execution!",
    "You've just taken a major step towards success!",
    "Your actions are a testament to your acumen and skill!",
    "Incredibly well done—your strategy was perfect!",
    "You've just navigated that perfectly—impressive precision!",
    "You're reshaping the landscape with your brilliant moves!",
    "Your performance is a beacon of excellence and creativity!",
    "That was a vital step excellently taken—congrats!",
    "You've aced that task with incredible finesse!",
    "Remarkable execution—your dedication is evident!",
    "You're defining the contours of success with each step!",
    "What a strategic triumph—truly commendable!",
    "Your actions have paved the way for outstanding results!",
    "You've turned what seemed hard into something stellar!",
    "Impressive breakthrough with your recent moves!",
    "Your prowess in handling this is unmatched!",
    "That was not only good—it was trailblazing!",
    "You've demonstrated profound wisdom in your approach!",
    "Each step you take sets a new benchmark for success!",
    "You're crafting a narrative of victory with your actions!",
    "Your choice was not just good; it was visionary!",
    "You've brilliantly surpassed the expectations!",
    "What a phenomenal strategy you've employed!",
    "You're consistently making all the right moves!",
    "You've just advanced your cause spectacularly!",
    "That was a deeply strategic and effective action!",
    "Your vision for this project is being brilliantly realized!",
    "What a powerful execution of a brilliant strategy!",
    "You've just set a new standard for excellence!",
    "You're not just participating; you're leading the way!"
]

hn_target_templates=[
    "It's not a good strategy to remain stagnant towards {target}.",
    "Failing to make significant progress towards {target} isn't wise.",
    "It's detrimental not to advance effectively towards {target}.",
    "Not moving decisively towards {target} is a missed opportunity.",
    "You're not taking effective steps towards {target}, which is concerning.",
    "It's unwise to delay progress towards {target}.",
    "Avoiding significant strides towards {target} could be harmful.",
    "It's a setback not to be moving effectively towards {target}.",
    "You should reconsider your approach if you're not progressing towards {target}.",
    "Lack of effective movement towards {target} is not beneficial.",
    "It's not advantageous to stall on the way to {target}.",
    "It's a strategic misstep not advancing towards {target}.",
    "Your current stagnation in moving towards {target} is problematic.",
    "It's a poor choice to not actively pursue {target}.",
    "You're missing crucial progress towards {target} by not advancing.",
    "It's unproductive to remain idle regarding progress towards {target}.",
    "Failing to approach {target} actively is a negative move.",
    "It's ineffective to not make headway towards {target}.",
    "Your inaction towards achieving {target} is not a good strategy.",
    "It's counterproductive not to push forward towards {target}.",
    "You're not making the necessary advances towards {target}, which is critical.",
    "Not accelerating towards {target} is a tactical error.",
    "It's disadvantageous not making progress towards {target}.",
    "Stalling on progress towards {target} is a poor decision.",
    "Your lack of motion towards {target} is not helping.",
    "Not progressing effectively towards {target} is a serious oversight.",
    "It's a concern not to be actively moving towards {target}.",
    "You're not heading in the right direction towards {target} effectively.",
    "Hesitating to move decisively towards {target} is an ill-advised strategy.",
    "It's an unfavorable move to not be progressing towards {target}.",
    "Neglecting to make strides towards {target} is detrimental.",
    "It's not wise to lag behind on the journey towards {target}.",
    "A lack of effective advancement towards {target} is inadvisable.",
    "It's a mistake not pushing towards {target} with urgency.",
    "Falling short of making progress towards {target} is not recommended.",
    "Your hesitance to advance towards {target} is proving costly.",
    "It's not ideal to dawdle on the way to {target}.",
    "Lack of decisive action towards {target} is a critical misstep.",
    "Not pursuing {target} effectively is clearly a mistake.",
    "Your slow progress towards {target} is not sufficient.",
    "It's a regrettable oversight to not move effectively towards {target}.",
    "Your reluctance to advance towards {target} is concerning.",
    "It's a blunder to not focus on progressing towards {target}.",
    "You're not effectively targeting your efforts towards {target}, which is essential.",
    "Failing to close in on {target} effectively is a negative strategy.",
    "Not working swiftly towards {target} is a lapse in judgment.",
    "It's not advantageous to drift away from making progress towards {target}.",
    "A lack of urgency in moving towards {target} is ill-advised.",
    "Your approach to not effectively moving towards {target} is flawed.",
    "It's inadvisable to not make consistent efforts towards {target}.",
    "Stagnation in the face of needing to reach {target} is not effective.",
    "It's a significant misjudgment not making headway towards {target}.",
    "It's ill-judged to not be effectively marching towards {target}.",
    "Your tactics of not moving towards {target} are not proving successful.",
    "It's inappropriate to not accelerate progress towards {target}.",
    "Not carving a path towards {target} effectively is a misstep.",
    "The failure to navigate effectively towards {target} is a major drawback.",
    "It's a deficiency not to be advancing efficiently towards {target}.",
    "You're not making essential progress towards {target}, which is pivotal.",
    "It's disadvantageous to not be closing in on {target}.",
    "Your current pace towards {target} is inadequately slow.",
    "Not advancing towards {target} effectively is a crucial mistake.",
    "It's problematic that you're not making substantial progress towards {target}.",
    "Holding back from moving decisively towards {target} is not helping.",
    "You're failing to capitalize on moving towards {target} efficiently.",
    "It's not prudent to be this passive about reaching {target}.",
    "Stagnating instead of progressing towards {target} is a negative approach.",
    "Your lack of urgency in approaching {target} is a strategic flaw.",
    "It's a misstep to not be making strides towards {target}.",
    "Not forging ahead towards {target} effectively is a poor tactic.",
    "You're not achieving the necessary momentum towards {target}.",
    "Failing to progress towards {target} is setting you back significantly.",
    "Not moving towards {target} with purpose is a substantial error.",
    "Your approach lacks the necessary drive to reach {target} effectively.",
    "Lagging in your efforts towards {target} is not advisable.",
    "It's a strategic error to not be advancing towards {target} effectively.",
    "Your slow approach towards {target} could be costly.",
    "Not pushing forward towards {target} is a gap in your strategy.",
    "It's concerning to see the lack of progress towards {target}.",
    "Your passive stance on moving towards {target} is a problem.",
    "It's a regrettable choice to not be actively pursuing {target}.",
    "Not making effective moves towards {target} could be a critical failure.",
    "You're not harnessing your potential to advance towards {target}.",
    "It's counterproductive to not focus your efforts on {target}.",
    "You're not demonstrating the required urgency towards {target}.",
    "A lack of forward motion towards {target} is a glaring issue.",
    "It's unsatisfactory to not be making progress towards {target}.",
    "Your reluctance to move towards {target} swiftly is a tactical blunder.",
    "Not aiming directly towards {target} is proving to be a misstep.",
    "You're missing out by not actively progressing towards {target}.",
    "Your approach to {target} is too tentative to be effective.",
    "It's unwise to not be proactively moving towards {target}.",
    "You're not taking the necessary steps to efficiently reach {target}.",
    "Not striving aggressively towards {target} is a mistake.",
    "Failing to steer towards {target} effectively is a missed opportunity.",
    "Your lack of decisive moves towards {target} is concerning.",
    "It's not beneficial to be idle in your pursuit of {target}.",
    "Your efforts towards {target} need more momentum.",
    "It's inefficient to not be pushing towards {target} with force.",
    "Your current strategy towards {target} is lacking effectiveness.",
    "Not progressing assertively towards {target} is a shortfall.",
    "It's disadvantageous to not be aggressively moving towards {target}.",
    "You're falling behind by not effectively targeting {target}.",
    "It's a concern that you're not making necessary strides towards {target}.",
    "Your lack of progress towards {target} is a critical concern.",
    "It's unhelpful to not be dynamically moving towards {target}.",
    "You're not meeting the required pace towards {target}.",
    "Not engaging fully in moving towards {target} is a liability.",
    "It's inadequate to not be advancing steadily towards {target}.",
    "Your minimal progress towards {target} is not sufficient.",
    "It's unproductive to not be actively engaging with {target}.",
    "You're not moving towards {target} with the needed determination.",
    "Lacking momentum towards {target} is a strategic oversight.",
    "It's a misjudgment to not be vigorously pursuing {target}.",
    "Your actions towards {target} are not translating into progress.",
    "Your progress towards {target} lacks the necessary urgency.",
    "It's a failure to not actively push towards {target}.",
    "Not making headway towards {target} is a glaring deficiency.",
    "It's unproductive to hover around without progressing towards {target}.",
    "Your approach to reaching {target} is notably ineffective.",
    "Not driving forward towards {target} is a strategic misfire.",
    "You're missing the mark on making necessary progress towards {target}.",
    "It's a negative to remain static instead of moving towards {target}.",
    "Lack of progress towards {target} signifies a tactical error.",
    "Not propelling forward towards {target} is not the way to go.",
    "Your actions are insufficient for reaching {target} efficiently.",
    "Failing to advance towards {target} effectively is a setback.",
    "It's detrimental to just tread water instead of advancing towards {target}.",
    "You're falling short of making significant strides towards {target}.",
    "It's a critical error to not make efficient progress towards {target}.",
    "Not moving towards {target} with clarity and purpose is unhelpful.",
    "You're not making the necessary progress towards {target}—that's concerning.",
    "It's disadvantageous to not take decisive action towards {target}.",
    "Your passive approach towards {target} is a major drawback.",
    "It's a lapse in strategy to not be aiming directly at {target}.",
    "You're not approaching {target} with the necessary precision.",
    "Stagnation in moving towards {target} is not a viable option.",
    "Not closing in on {target} actively is an oversight.",
    "It's problematic to not be progressing meaningfully towards {target}.",
    "You're not effectively navigating towards {target}—that needs to change.",
    "Your lackluster efforts towards {target} are not yielding results.",
    "Not pushing aggressively towards {target} is a mistake.",
    "It's imprudent to not make considerable progress towards {target}.",
    "You're not advancing towards {target} in a productive manner.",
    "Failing to make effective gains towards {target} is ill-advised.",
    "You're not utilizing your full potential to reach {target}.",
    "It's unwise to be complacent about progressing towards {target}.",
    "Your tepid progress towards {target} is not satisfactory.",
    "Not moving towards {target} with vigor is a strategic lapse.",
    "You're not taking effective steps towards {target}—this is a misstep.",
    "It's not constructive to be idle when you should be moving towards {target}.",
    "Your slow pace towards {target} is detrimental to success.",
    "Not advancing effectively towards {target} shows a lack of commitment.",
    "It's essential to pick up the pace towards {target}—you're falling behind.",
    "Not accelerating your efforts towards {target} is a poor choice.",
    "It's regrettable to see such minimal progress towards {target}.",
    "You need to step up your efforts to effectively reach {target}.",
    "Not progressing dynamically towards {target} is a point of concern.",
    "It's a poor execution to not be making strides towards {target}.",
    "You're not heading towards {target} with enough determination.",
    "A lack of impactful actions towards {target} is a flaw in your approach.",
    "It's a drawback to not be moving decisively towards {target}.",
    "Your approach to {target} is too passive and unproductive.",
    "You're not adequately targeting {target}—that needs correction.",
    "Not pushing towards {target} with adequate force is an error.",
    "Your current trajectory towards {target} is underwhelming.",
    "It's a miss to not be effectively reaching towards {target}.",
    "Not making rapid progress towards {target} is a concern.",
    "You're not making the essential advancements towards {target}.",
    "Your lack of decisive steps towards {target} is troubling.",
    "It's a misjudgment to not be aggressively pursuing {target}.",
    "Your efforts to reach {target} are lacking in intensity.",
    "You're not effectively charging towards {target}—that's critical."
]

hn_enemy_templates=[
    "You should be steering clear of {enemy_name}.",
    "It's not wise to keep engaging with {enemy_name}.",
    "Avoiding {enemy_name} should be a priority.",
    "It's detrimental that you're not avoiding {enemy_name}.",
    "You need to keep a distance from {enemy_name}.",
    "Staying away from {enemy_name} is crucial.",
    "It's risky to not avoid {enemy_name}.",
    "You're making a mistake by not avoiding {enemy_name}.",
    "Your approach should include staying away from {enemy_name}.",
    "It's unsafe to be near {enemy_name}.",
    "It's a poor strategy to not avoid {enemy_name}.",
    "You ought to be distancing yourself from {enemy_name}.",
    "Not avoiding {enemy_name} is a bad idea.",
    "You should rethink your proximity to {enemy_name}.",
    "Avoiding {enemy_name} would be a wise decision.",
    "It's concerning that you're not steering clear of {enemy_name}.",
    "You're taking unnecessary risks with {enemy_name}.",
    "Keeping away from {enemy_name} is advisable.",
    "It's a bad move to keep encountering {enemy_name}.",
    "Distancing yourself from {enemy_name} is essential.",
    "You should be making efforts to avoid {enemy_name}.",
    "It's unwise to be around {enemy_name}.",
    "Staying out of {enemy_name}'s way is necessary.",
    "You're not doing well by staying close to {enemy_name}.",
    "It's critical to avoid contact with {enemy_name}.",
    "Evading {enemy_name} is a must.",
    "It's essential to keep your distance from {enemy_name}.",
    "You're making an error by not avoiding {enemy_name}.",
    "It's advisable to stay clear of {enemy_name}.",
    "You should prioritize avoiding {enemy_name}.",
    "Being close to {enemy_name} is not beneficial.",
    "You're jeopardizing safety by not avoiding {enemy_name}.",
    "Avoiding {enemy_name} is key to your well-being.",
    "It's a strategic mistake to interact with {enemy_name}.",
    "Staying clear of {enemy_name} should be your focus.",
    "It's a lapse in judgment not to avoid {enemy_name}.",
    "Keeping a safe distance from {enemy_name} is wise.",
    "You shouldn't underestimate the need to avoid {enemy_name}.",
    "It's pivotal that you steer clear of {enemy_name}.",
    "Your current strategy should involve avoiding {enemy_name}.",
    "It's not safe to be in proximity to {enemy_name}.",
    "You're not taking the right precautions with {enemy_name}.",
    "Staying far from {enemy_name} is the best course of action.",
    "You're overlooking the dangers of {enemy_name}.",
    "It's necessary to avoid interactions with {enemy_name}.",
    "Being around {enemy_name} is a clear risk.",
    "It's imprudent to not distance yourself from {enemy_name}.",
    "You should avoid {enemy_name} at all costs.",
    "Not steering clear of {enemy_name} is problematic.",
    "You need to take action to evade {enemy_name}.",
    "Avoiding {enemy_name} is crucial for safety.",
    "It's a bad practice to not avoid {enemy_name}.",
    "You need to reconsider your approach towards {enemy_name}.",
    "Staying out of reach from {enemy_name} is a necessity.",
    "It's not strategic to interact with {enemy_name}.",
    "You should be working harder to avoid {enemy_name}.",
    "Not avoiding {enemy_name} is a tactical error.",
    "Keeping clear from {enemy_name} is critical for your plans.",
    "You're exposing yourself unnecessarily by not avoiding {enemy_name}.",
    "It's a failure in strategy to not keep away from {enemy_name}.",
     "It's vital that you avoid {enemy_name} at this point.",
    "You're taking a gamble by not staying away from {enemy_name}.",
    "It's unadvisable to remain in close quarters with {enemy_name}.",
    "Your safety depends on avoiding {enemy_name}.",
    "It's crucial that you maintain a distance from {enemy_name}.",
    "You need to focus on keeping {enemy_name} at bay.",
    "Not avoiding {enemy_name} could lead to significant risks.",
    "You should be actively working to stay clear of {enemy_name}.",
    "It's in your best interest to steer away from {enemy_name}.",
    "Avoiding {enemy_name} should be top of your agenda.",
    "You are risking too much by not avoiding {enemy_name}.",
    "It's a strategic necessity to avoid {enemy_name}.",
    "Keeping {enemy_name} out of your path is essential.",
    "It's impractical to not avoid {enemy_name}.",
    "You're inviting trouble by not avoiding {enemy_name}.",
    "It's hazardous to keep interacting with {enemy_name}.",
    "You should make it a priority to avoid {enemy_name}.",
    "It's unwise to let your guard down around {enemy_name}.",
    "Staying away from {enemy_name} is imperative.",
    "You need a solid plan to avoid {enemy_name}.",
    "It's not in your best interest to engage with {enemy_name}.",
    "You're compromising your position by not avoiding {enemy_name}.",
    "You must take measures to avoid {enemy_name}.",
    "It's essential to circumvent any interaction with {enemy_name}.",
    "Keeping distance from {enemy_name} is a priority.",
    "You should be avoiding {enemy_name} more carefully.",
    "It's unwise to keep {enemy_name} within reach.",
    "You're making a tactical mistake by not avoiding {enemy_name}.",
    "Avoiding {enemy_name} is critical for your security.",
    "You need to stay far away from {enemy_name}.",
    "Not avoiding {enemy_name} is a clear misstep.",
    "It's key that you keep {enemy_name} out of your proximity.",
    "You're not safeguarding yourself by staying near {enemy_name}.",
    "It's vital to distance yourself from {enemy_name}.",
    "You should have no dealings with {enemy_name}.",
    "Not avoiding {enemy_name} is not just bad, it's dangerous.",
    "You need to ensure you're not around {enemy_name}.",
    "It's advisable to eliminate any interaction with {enemy_name}.",
    "You should be more diligent in avoiding {enemy_name}.",
    "You're not being cautious enough around {enemy_name}.",
    "Steering clear of {enemy_name} is your best strategy.",
    "You should avoid any encounters with {enemy_name}.",
    "It's a poor decision to not avoid {enemy_name}.",
    "Keeping away from {enemy_name} should be obvious.",
    "You should intensify efforts to avoid {enemy_name}.",
    "It's a lack of foresight to not steer clear of {enemy_name}.",
    "Avoiding {enemy_name} is non-negotiable.",
    "You're not taking the necessary steps to avoid {enemy_name}.",
    "It's a must to keep away from {enemy_name}.",
    "You're not making smart choices regarding {enemy_name}.",
    "It's critical to put distance between yourself and {enemy_name}.",
    "You should be more proactive about avoiding {enemy_name}.",
    "It's a fundamental mistake to not avoid {enemy_name}.",
    "Your approach towards {enemy_name} needs revising.",
    "You must rethink your proximity to {enemy_name}.",
    "You're not doing enough to avoid {enemy_name}.",
    "It's essential to break away from {enemy_name}.",
    "You're failing to keep a safe distance from {enemy_name}.",
    "Not avoiding {enemy_name} is a strategic blunder.",
    "It's a grave error to not maintain distance from {enemy_name}.",
    "You're putting yourself at risk by not avoiding {enemy_name}.",
    "It's negligent to not steer clear of {enemy_name}.",
    "You're not taking the necessary precautions with {enemy_name}.",
    "Failing to avoid {enemy_name} is a direct threat to your safety.",
    "It's crucial to sidestep any encounters with {enemy_name}.",
    "You should be making every effort to avoid {enemy_name}.",
    "Engaging with {enemy_name} is not advisable under any circumstances.",
    "You need to be more vigilant about keeping away from {enemy_name}.",
    "It's imperative to avoid any interaction with {enemy_name}.",
    "Not keeping a safe distance from {enemy_name} is a serious lapse.",
    "You're not handling the situation with {enemy_name} appropriately.",
    "It's unwise to underestimate the importance of avoiding {enemy_name}.",
    "Your approach to dealing with {enemy_name} needs urgent reassessment.",
    "Avoiding {enemy_name} is vital for maintaining safety.",
    "You're too close for comfort to {enemy_name}.",
    "You need to prioritize safety by avoiding {enemy_name}.",
    "It's careless to not distance yourself from {enemy_name}.",
    "You must avoid {enemy_name} to safeguard your interests.",
    "Failing to keep {enemy_name} at arm's length is imprudent.",
    "You're not making wise decisions regarding {enemy_name}.",
    "It's essential to put considerable distance between yourself and {enemy_name}.",
    "You're not being strategic about avoiding {enemy_name}.",
    "Avoiding {enemy_name} should be an absolute priority.",
    "You should be avoiding {enemy_name} with greater diligence.",
    "Not avoiding {enemy_name} is asking for trouble.",
    "It's a critical oversight to not avoid {enemy_name}.",
    "You need to adjust your strategy to avoid {enemy_name} more effectively.",
    "Not staying away from {enemy_name} is a poor choice.",
    "It's necessary to rethink your proximity to {enemy_name}.",
    "You're underestimating the need to steer clear of {enemy_name}.",
    "Failing to distance yourself from {enemy_name} is a misstep.",
    "You must take more aggressive actions to avoid {enemy_name}.",
    "It's not acceptable to remain so close to {enemy_name}.",
    "You should be more resolute in avoiding {enemy_name}.",
    "It's not sufficient to just be cautious around {enemy_name}.",
    "Avoiding {enemy_name} is the only sensible course of action.",
    "You're overlooking the necessity to keep away from {enemy_name}.",
    "It's unwise to be passive about avoiding {enemy_name}.",
    "Your casual approach to {enemy_name} is inadequate.",
    "You need a stronger plan to avoid {enemy_name}.",
    "It's crucial to eliminate any risk of contact with {enemy_name}.",
    "You're not making enough effort to steer clear of {enemy_name}.",
    "It's risky to continue interactions with {enemy_name}.",
    "Not avoiding {enemy_name} effectively is a strategic error.",
    "You should be taking every precaution to avoid {enemy_name}.",
    "Failing to avoid {enemy_name} could have severe consequences.",
    "It's not just unwise, it's dangerous to not avoid {enemy_name}.",
    "You must be more proactive in avoiding {enemy_name}.",
    "You're failing to avoid {enemy_name} and it's not safe.",
    "It's important to rethink how you're handling {enemy_name}.",
    "You should be doing everything possible to avoid {enemy_name}.",
    "It's critical to avoid any sort of engagement with {enemy_name}.",
    "You need to be avoiding {enemy_name} at all costs.",
    "Your current approach to {enemy_name} is too lax.",
    "It's a serious error to not be avoiding {enemy_name}.",
    "You must work harder to keep away from {enemy_name}.",
    "Not avoiding {enemy_name} shows a lack of foresight.",
    "You're not doing enough to distance yourself from {enemy_name}."
]

fp_oracle_direct=[
    "Move {optimal_direction} to approach the {target_name}. ",
    "Head {optimal_direction} to get closer to {target_name}. ",
    "Go {optimal_direction} if you want to find {target_name}. ",
    "Take a {optimal_direction} turn towards {target_name}. ",
    "Moving {optimal_direction} will lead you to {target_name}. ",
    "Start heading {optimal_direction} to reach {target_name}. ",
    "Make your way {optimal_direction} to see {target_name}. ",
    "To meet {target_name}, just go {optimal_direction}. ",
    "A quick {optimal_direction} move gets you to {target_name}. ",
    "For {target_name}, aim {optimal_direction}. ",
    "If {target_name} is your goal, {optimal_direction} is the way. ",
    "Travel {optimal_direction} to approach {target_name}. ",
    "Walk {optimal_direction} for {target_name}. ",
    "To catch up with {target_name}, head {optimal_direction}. ",
    "Moving {optimal_direction} gets you closer to {target_name}. ",
    "For a direct path to {target_name}, go {optimal_direction}. ",
    "Journey {optimal_direction} towards {target_name}. ",
    "To spot {target_name}, move {optimal_direction}. ",
    "Navigate {optimal_direction} to find {target_name}. ",
    "To link up with {target_name}, proceed {optimal_direction}. ",
    "Step {optimal_direction} nearer to {target_name}. ",
    "Pursue the path {optimal_direction} to {target_name}. ",
    "Follow along {optimal_direction} to see {target_name}. ",
    "Traverse {optimal_direction} closer to {target_name}. ",
    "Cover ground {optimal_direction} towards {target_name}. ",
    "Embark {optimal_direction} to find {target_name}. ",
    "Forge ahead {optimal_direction} towards {target_name}. ",
    "Paddle {optimal_direction} to reach {target_name}. ",
    "Sail {optimal_direction} towards {target_name}. ",
    "Drive {optimal_direction} to approach {target_name}. ",
    "Fly {optimal_direction} to meet {target_name}. ",
    "Cruise {optimal_direction} to get closer to {target_name}. ",
    "Roll {optimal_direction} towards {target_name}. ",
    "Run {optimal_direction} to find {target_name}. ",
    "Jog {optimal_direction} to reach {target_name}. ",
    "Sprint {optimal_direction} towards {target_name}. ",
    "Race {optimal_direction} to approach {target_name}. ",
    "Dash {optimal_direction} to get to {target_name}. ",
    "Hurry {optimal_direction} towards {target_name}. ",
    "Speed {optimal_direction} near {target_name}. ",
    "Bolt {optimal_direction} to find {target_name}. ",
    "Gallop {optimal_direction} to meet {target_name}. ",
    "Charge {optimal_direction} towards {target_name}. ",
    "Make a move {optimal_direction} to reach {target_name}. ",
    "Adjust your route {optimal_direction} for {target_name}. ",
    "Redirect {optimal_direction} to approach {target_name}. ",
    "Set off {optimal_direction} towards {target_name}. ",
    "Begin your journey {optimal_direction} to find {target_name}. ",
    "Start heading {optimal_direction} to get closer to {target_name}. ",
    "Kick off {optimal_direction} towards {target_name}. ",
    "Embark on a path {optimal_direction} to see {target_name}. ",
    "Launch towards {optimal_direction} to find {target_name}. ",
    "Set your course {optimal_direction} towards {target_name}. ",
    "Make tracks {optimal_direction} to approach {target_name}. ",
    "Start off {optimal_direction} towards {target_name}. ",
    "Head out {optimal_direction} to meet {target_name}. ",
    "Go {optimal_direction} towards the {target_name}. ",
    "Head {optimal_direction} to get closer to {target_name}. ",
    "Proceed {optimal_direction} to reach {target_name}. ",
    "Move {optimal_direction} to find {target_name}. ",
    "Walk {optimal_direction} to approach {target_name}. ",
    "Take a step {optimal_direction} nearer to {target_name}. ",
    "Navigate {optimal_direction} to come closer to {target_name}. ",
    "Advance {optimal_direction} to head towards {target_name}. ",
    "Turn {optimal_direction} to face {target_name}. ",
    "Journey {optimal_direction} to locate {target_name}. ",
    "Push {optimal_direction} to meet {target_name}. ",
    "Drift {optimal_direction} to find your way to {target_name}. ",
    "Lean {optimal_direction} to aim for {target_name}. ",
    "Make your way {optimal_direction} to {target_name}. ",
    "Stroll {optimal_direction} to discover {target_name}. ",
    "March {optimal_direction} towards {target_name}. ",
    "Follow {optimal_direction} to reach {target_name}. ",
    "Use {optimal_direction} direction to get to {target_name}. ",
    "Shift {optimal_direction} towards {target_name}. ",
    "Guide yourself {optimal_direction} to {target_name}. ",
    "Move towards {optimal_direction} to get to {target_name}. ",
    "Aim {optimal_direction} to close in on {target_name}. ",
    "Set your path {optimal_direction} to meet {target_name}. ",
    "Direct your steps {optimal_direction} to {target_name}. ",
    "Orient yourself {optimal_direction} towards {target_name}. ",
    "Proceed in the {optimal_direction} direction to find {target_name}. ",
    "Step {optimal_direction} to get nearer to {target_name}. ",
    "Head in the {optimal_direction} direction to approach {target_name}. ",
    "Make a move {optimal_direction} to encounter {target_name}. ",
    "Start moving {optimal_direction} towards {target_name}. ",
    "Take your way {optimal_direction} to see {target_name}. ",
    "March on {optimal_direction} to find {target_name}. ",
    "Keep going {optimal_direction} to get to {target_name}. ",
    "Continue {optimal_direction} to close the distance to {target_name}. ",
    "Press on {optimal_direction} towards {target_name}. ",
    "Advance in the {optimal_direction} direction to {target_name}. ",
    "Push forward {optimal_direction} to {target_name}. ",
    "Travel {optimal_direction} near {target_name}. ",
    "Proceed directly {optimal_direction} towards {target_name}. ",
    "Migrate {optimal_direction} to encounter {target_name}. ",
    "Hike {optimal_direction} to get close to {target_name}. ",
    "Tread {optimal_direction} towards {target_name}. ",
    "Forge ahead {optimal_direction} to {target_name}. ",
    "Venture {optimal_direction} towards {target_name}. ",
    "Set out {optimal_direction} to reach {target_name}. ",
    "Embark {optimal_direction} to connect with {target_name}. ",
    "Initiate your journey {optimal_direction} to {target_name}. ",
    "Begin moving {optimal_direction} to link up with {target_name}. ",
    "Launch {optimal_direction} to come near {target_name}. ",
    "Go {optimal_direction} to get closer to {target_name}. ",
    "Move {optimal_direction} to approach {target_name}. ",
    "Walk {optimal_direction} to reach {target_name}. ",
    "Run {optimal_direction} towards {target_name}. ",
    "Step {optimal_direction} to draw nearer to {target_name}. ",
    "Jog {optimal_direction} to move closer to {target_name}. ",
    "Head {optimal_direction} to meet {target_name}. ",
    "Travel {optimal_direction} to encounter {target_name}. ",
    "Proceed {optimal_direction} to engage with {target_name}. ",
    "Hurry {optimal_direction} to connect with {target_name}. ",
    "Dash {optimal_direction} to be near {target_name}. ",
    "Sprint {optimal_direction} to join {target_name}. ",
    "Shift {optimal_direction} to converge on {target_name}. ",
    "Turn {optimal_direction} to align with {target_name}. ",
    "Push {optimal_direction} to get in touch with {target_name}. ",
    "Pull {optimal_direction} towards {target_name}. ",
    "Drive {optimal_direction} to close in on {target_name}. ",
    "Drag {optimal_direction} to be closer to {target_name}. ",
    "Roll {optimal_direction} towards {target_name}. ",
    "Rush {optimal_direction} to be alongside {target_name}. ",
    "Flee {optimal_direction} towards {target_name}. ",
    "Escape {optimal_direction} to {target_name}. ",
    "Retreat {optimal_direction} towards {target_name}. ",
    "Back up {optimal_direction} to {target_name}. ",
    "Reverse {optimal_direction} to near {target_name}. ",
    "Recede {optimal_direction} towards {target_name}. ",
    "Part {optimal_direction} towards {target_name}. ",
    "Leave {optimal_direction} for {target_name}. ",
    "Exit {optimal_direction} towards {target_name}. ",
    "Depart {optimal_direction} to {target_name}. ",
    "Scramble {optimal_direction} towards {target_name}. ",
    "Scurry {optimal_direction} to {target_name}. ",
    "Speed {optimal_direction} to be next to {target_name}. ",
    "Race {optimal_direction} to {target_name}. ",
    "Pace {optimal_direction} to get nearer {target_name}. ",
    "Hike {optimal_direction} to find {target_name}. ",
    "Trot {optimal_direction} to {target_name}. ",
    "Lope {optimal_direction} to link with {target_name}. ",
    "Stride {optimal_direction} to {target_name}. ",
    "March {optimal_direction} to join {target_name}. ",
    "Amble {optimal_direction} to {target_name}. ",
    "Trudge {optimal_direction} to reach {target_name}. ",
    "Stagger {optimal_direction} towards {target_name}. ",
    "Stomp {optimal_direction} to {target_name}. ",
    "Slog {optimal_direction} to get closer to {target_name}. ",
    "Bolt {optimal_direction} to be next to {target_name}. ",
    "Bound {optimal_direction} to meet {target_name}. ",
    "Skip {optimal_direction} to see {target_name}. ",
    "Hop {optimal_direction} to be with {target_name}. ",
    "Leap {optimal_direction} to approach {target_name}. ",
    "Spring {optimal_direction} to encounter {target_name}. ",
    "Vault {optimal_direction} to reach {target_name}. ",
    "Duck {optimal_direction} to get to {target_name}. ",
    "Dodge {optimal_direction} to find {target_name}. ",
    "Sidestep {optimal_direction} to link with {target_name}. ",
    "Bypass {optimal_direction} to meet {target_name}. ",
    "Circumvent {optimal_direction} to be with {target_name}. ",
    "Skirt {optimal_direction} to catch up with {target_name}. ",
    "Evade {optimal_direction} to join {target_name}. ",
    "Elude {optimal_direction} to meet up with {target_name}. ",
    "Shun {optimal_direction} to be near {target_name}. ",
    "Avoid {optimal_direction} to come close to {target_name}. ",
    "Steer {optimal_direction} to gather near {target_name}. ",
    "Navigate {optimal_direction} to reach out to {target_name}. ",
    "Maneuver {optimal_direction} to be next to {target_name}. ",
    "Pilot {optimal_direction} to rendezvous with {target_name}. ",
    "Guide {optimal_direction} to be closer to {target_name}. ",
    "Direct your steps {optimal_direction} to align with {target_name}. ",
    "Handle {optimal_direction} to converge with {target_name}. ",
    "Control {optimal_direction} to reach {target_name}. ",
    "Command {optimal_direction} to approach {target_name}. "
]

fp_oracle_indirect=[
"Just step {optimal_direction} to keep away from the {target_name}.",
    "Quickly move {optimal_direction} to sidestep the {target_name}.",
    "Simply go {optimal_direction} to bypass the {target_name}.",
    "Casually walk {optimal_direction} to steer clear of the {target_name}.",
    "Gently turn {optimal_direction} to dodge the {target_name}.",
    "Easily head {optimal_direction} to get past the {target_name}.",
    "Swiftly shift {optimal_direction} to avoid the {target_name}.",
    "Directly move {optimal_direction} to keep a safe distance from the {target_name}.",
    "Carefully step {optimal_direction} away from the {target_name}.",
    "Quickly go {optimal_direction} to evade the {target_name}.",
    "Smoothly walk {optimal_direction} to get around the {target_name}.",
    "Slowly turn {optimal_direction} and avoid the {target_name}.",
    "Promptly head {optimal_direction} to distance yourself from the {target_name}.",
    "Lightly shift {optimal_direction} to clear the {target_name}.",
    "Actively move {optimal_direction} to escape the {target_name}.",
    "Conveniently step {optimal_direction} to stay clear of the {target_name}.",
    "Normally go {optimal_direction} to get away from the {target_name}.",
    "Deliberately walk {optimal_direction} to outmaneuver the {target_name}.",
    "Intentionally turn {optimal_direction} to bypass the {target_name}.",
    "Safely head {optimal_direction} to steer away from the {target_name}.",
    "Confidently shift {optimal_direction} to dodge the {target_name}.",
    "Subtly move {optimal_direction} and avoid the {target_name}.",
    "Simply move {optimal_direction} to avoid the {target_name}.",
    "Take a step {optimal_direction} to steer clear of the {target_name}.",
"Step {optimal_direction} to stay out of the {target_name}'s way.",
"Shift {optimal_direction} to keep your distance from the {target_name}.",
"Just step {optimal_direction} to stay away from the {target_name}.",
"Move {optimal_direction} to maintain distance from the {target_name}.",
"Head {optimal_direction} to avoid contact with the {target_name}.",
"Step {optimal_direction} to dodge the {target_name}.",
"Take a quick step {optimal_direction} to avoid the {target_name}.",
"Go {optimal_direction} to stay away from the {target_name}.",
"Just move {optimal_direction} to keep yourself away from the {target_name}.",
"Shift your position {optimal_direction} to avoid the {target_name}.",
"Step {optimal_direction} to evade the {target_name}.",
"Take a step {optimal_direction} to steer away from the {target_name}.",
"Just head {optimal_direction} to distance yourself from the {target_name}."
    "Calmly step {optimal_direction} to clear the path from the {target_name}.",
    "Efficiently go {optimal_direction} to sidestep the {target_name}.",
    "Purposefully walk {optimal_direction} to avoid the {target_name}.",
    "Strategically turn {optimal_direction} to keep away from the {target_name}.",
    "Simply head {optimal_direction} to elude the {target_name}.",
    "Quickly shift {optimal_direction}, moving clear of the {target_name}.",
    "Carefully move {optimal_direction} to miss the {target_name}.",
    "Casually step {optimal_direction} to get around the {target_name}.",
    "Directly go {optimal_direction} to steer clear of any trouble with the {target_name}.",
    "Easily walk {optimal_direction} to keep a good distance from the {target_name}.",
    "Smoothly turn {optimal_direction} to stay out of reach of the {target_name}.",
    "Gently head {optimal_direction} to bypass any interaction with the {target_name}.",
    "Swiftly shift {optimal_direction} to steer away from the {target_name}.",
    "Directly move {optimal_direction} to distance yourself from the {target_name}.",
    "Lightly step {optimal_direction}, avoiding any close contact with the {target_name}.",
    "Normally go {optimal_direction}, keeping yourself far from the {target_name}.",
    "Deliberately walk {optimal_direction}, maintaining a safe distance from the {target_name}.",
    "Intentionally turn {optimal_direction}, moving away from the {target_name}.",
    "Safely head {optimal_direction}, escaping the reach of the {target_name}.",
    "Confidently shift {optimal_direction}, ensuring you stay away from the {target_name}.",
    "Subtly move {optimal_direction}, leaving the {target_name} behind.",
    "Calmly step {optimal_direction}, avoiding any confrontation with the {target_name}.",
    "Efficiently go {optimal_direction}, ensuring you remain out of the {target_name}'s way.",
     "Just step {optimal_direction} to keep a clear line away from the {target_name}.",
    "Quickly move {optimal_direction} and create some space from the {target_name}.",
    "Simply go {optimal_direction} to maintain distance from the {target_name}.",
    "Casually walk {optimal_direction} to get beyond the {target_name}.",
    "Gently turn {optimal_direction} to slip past the {target_name}.",
    "Easily head {optimal_direction} to remain out of the way of the {target_name}.",
    "Swiftly shift {optimal_direction} to get out from in front of the {target_name}.",
    "Directly move {optimal_direction} to keep off the path of the {target_name}.",
    "Carefully step {optimal_direction} to sidestep the {target_name}.",
    "Quickly go {optimal_direction} to detach yourself from the {target_name}.",
    "Smoothly walk {optimal_direction} to evade any interaction with the {target_name}.",
    "Slowly turn {optimal_direction} to gently avoid the {target_name}.",
    "Promptly head {optimal_direction} to put some distance between you and the {target_name}.",
    "Lightly shift {optimal_direction} to move aside from the {target_name}.",
    "Actively move {optimal_direction} to get a better position away from the {target_name}.",
    "Conveniently step {optimal_direction} to stay off the track of the {target_name}.",
    "Normally go {optimal_direction} to bypass the area near the {target_name}.",
    "Deliberately walk {optimal_direction} to keep yourself away from the {target_name}.",
    "Intentionally turn {optimal_direction} to remain out of touch from the {target_name}.",
    "Safely head {optimal_direction} to escape the vicinity of the {target_name}.",
    "Confidently shift {optimal_direction} to clear the area near the {target_name}.",
    "Subtly move {optimal_direction} to steer well clear of the {target_name}.",
    "Calmly step {optimal_direction} to calmly avoid the {target_name}.",
    "Efficiently go {optimal_direction} to move out of proximity to the {target_name}.",
    "Purposefully walk {optimal_direction} to avoid any close encounters with the {target_name}.",
    "Strategically turn {optimal_direction} to navigate away from the {target_name}.",
    "Simply head {optimal_direction} to maintain a safe barrier from the {target_name}.",
    "Quickly shift {optimal_direction}, dodging the {target_name} effectively.",
    "Carefully move {optimal_direction} to avert any contact with the {target_name}.",
    "Casually step {optimal_direction}, keeping it casual yet safe from the {target_name}.",
    "Directly go {optimal_direction}, cutting straight away from the {target_name}.",
    "Easily walk {optimal_direction}, making it look easy to avoid the {target_name}.",
    "Smoothly turn {optimal_direction}, gracefully avoiding the {target_name}.",
    "Gently head {optimal_direction}, making sure to stay away from the {target_name}.",
    "Swiftly shift {optimal_direction}, briskly moving past the {target_name}.",
    "Directly move {optimal_direction}, making a direct line away from the {target_name}.",
    "Lightly step {optimal_direction}, lightly tiptoeing away from the {target_name}.",
    "Normally go {optimal_direction}, as if it's just a normal move away from the {target_name}.",
    "Deliberately walk {optimal_direction}, with deliberate steps to steer clear of the {target_name}.",
    "Intentionally turn {optimal_direction}, turning your back on the {target_name}.",
    "Safely head {optimal_direction}, choosing the safest route away from the {target_name}.",
    "Confidently shift {optimal_direction}, confidently distancing yourself from the {target_name}.",
    "Subtly move {optimal_direction}, subtly making your way past the {target_name}.",
    "Calmly step {optimal_direction}, remaining calm as you pass the {target_name}.",
    "Efficiently go {optimal_direction}, efficiently making space between you and the {target_name}.",
    "Purposefully walk {optimal_direction}, with a purpose to avoid the {target_name}.",
    "Strategically turn {optimal_direction}, strategically placing yourself away from the {target_name}.",
    "Simply head {optimal_direction}, just simply heading in the other direction from the {target_name}.",
    "Quickly shift {optimal_direction}, quickly changing your trajectory from the {target_name}.",
    "Carefully move {optimal_direction}, being careful not to get too close to the {target_name}.",
    "Casually step {optimal_direction}, casually but cautiously avoiding the {target_name}.",
    "Directly go {optimal_direction}, making a beeline away from the {target_name}.",
    "Easily walk {optimal_direction}, easily sidestepping the {target_name}.",
    "Smoothly turn {optimal_direction}, smoothly curving away from the {target_name}.",
    "Gently head {optimal_direction}, gently curving away from any danger from the {target_name}.",
    "Swiftly shift {optimal_direction}, swiftly finding a safer spot away from the {target_name}.",
    "Directly move {optimal_direction}, moving directly to safer ground away from the {target_name}.",
    "Lightly step {optimal_direction}, stepping lightly as you move away from the {target_name}.",
    "Normally go {optimal_direction}, proceeding as though it's just another day avoiding the {target_name}.",
    "Deliberately walk {optimal_direction}, walking with intention away from the {target_name}.",
    "Intentionally turn {optimal_direction}, intentionally facing away from the {target_name}."
]

threshold={
    "hp_templates":{'testing_threshold':(81,100),'validation_threshold':(101,115),'training_threshold':{'template': 1, 'augmented': 80}},
    "hn_target_templates":{'testing_threshold':(81,100),'validation_threshold':(101,115),'training_threshold':{'template': 1, 'augmented': 80}},
    "hn_enemy_templates":{'testing_threshold':(81,100),'validation_threshold':(101,115),'training_threshold':{'template': 1,  'augmented': 80}},
    "fp_oracle_direct":{'testing_threshold':(81,100),'validation_threshold':(101,115),'training_threshold':{'template': 1, 'augmented': 80}},
    "fp_oracle_indirect":{'testing_threshold':(81,100),'validation_threshold':(101,115),'training_threshold':{'template': 1, 'augmented': 80}},
}

if __name__=="__main__":
    data=(hp_templates,hn_target_templates,hn_enemy_templates,fp_oracle_direct,fp_oracle_indirect)
    torch.save(data,"./languages.pth")
    torch.save(threshold,"./thresholds.pth")